// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = {[KeyType in keyof T]: T[KeyType]};

/**
 * Item in *resume → About tags*
 */
export interface ResumeDocumentDataAboutTagsItem {
  /**
   * Tag text field in *resume → About tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.about_tags[].tag_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag_text: prismic.KeyTextField;

  /**
   * Tag link field in *resume → About tags*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.about_tags[].tag_link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag_link: prismic.KeyTextField;
}

type ResumeDocumentDataSlicesSlice = never;

type ResumeDocumentDataSlices2Slice = EmployerSlice;

/**
 * Content for resume documents
 */
interface ResumeDocumentData {
  /**
   * About me blurb field in *resume*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.about_me_blurb
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_me_blurb: prismic.RichTextField;

  /**
   * About tags field in *resume*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.about_tags[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  about_tags: prismic.GroupField<Simplify<ResumeDocumentDataAboutTagsItem>>;

  /**
   * Slice Zone field in *resume*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ResumeDocumentDataSlicesSlice> /**
   * Meta Title field in *resume*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: resume.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *resume*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: resume.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *resume*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never> /**
   * Slice Zone field in *resume*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: resume.slices2[]
   * - **Tab**: Resume
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices2: prismic.SliceZone<ResumeDocumentDataSlices2Slice>;
}

/**
 * resume document from Prismic
 *
 * - **API ID**: `resume`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ResumeDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
  Simplify<ResumeDocumentData>,
  'resume',
  Lang
>;

export type AllDocumentTypes = ResumeDocument;

/**
 * Item in *Employer → Default → Primary → Position*
 */
export interface EmployerSliceDefaultPrimaryPositionItem {
  /**
   * Position name field in *Employer → Default → Primary → Position*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employer.default.primary.position[].position_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position_name: prismic.KeyTextField;

  /**
   * Position dates field in *Employer → Default → Primary → Position*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employer.default.primary.position[].position_dates
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  position_dates: prismic.KeyTextField;

  /**
   * Position blurb field in *Employer → Default → Primary → Position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employer.default.primary.position[].position_blurb
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  position_blurb: prismic.RichTextField;

  /**
   * Position tags field in *Employer → Default → Primary → Position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employer.default.primary.position[].position_tags
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  position_tags: prismic.RichTextField;
}

/**
 * Primary content in *Employer → Default → Primary*
 */
export interface EmployerSliceDefaultPrimary {
  /**
   * Employer name field in *Employer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: employer.default.primary.employer_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  employer_name: prismic.KeyTextField;

  /**
   * Position field in *Employer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: employer.default.primary.position[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  position: prismic.GroupField<Simplify<EmployerSliceDefaultPrimaryPositionItem>>;
}

/**
 * Default variation for Employer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmployerSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<EmployerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Employer*
 */
type EmployerSliceVariation = EmployerSliceDefault;

/**
 * Employer Shared Slice
 *
 * - **API ID**: `employer`
 * - **Description**: Employer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EmployerSlice = prismic.SharedSlice<'employer', EmployerSliceVariation>;

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ResumeDocument,
      ResumeDocumentData,
      ResumeDocumentDataAboutTagsItem,
      ResumeDocumentDataSlicesSlice,
      ResumeDocumentDataSlices2Slice,
      AllDocumentTypes,
      EmployerSlice,
      EmployerSliceDefaultPrimaryPositionItem,
      EmployerSliceDefaultPrimary,
      EmployerSliceVariation,
      EmployerSliceDefault
    };
  }
}
